### PR TITLE
Add CW audit log support to module

### PR DESCRIPTION
**Pull request by dpowley**
Adding support for CW audit logs and metrics

### CODE REVIEW

**Comment by ksatirli** [comment]
Thank you @dpowley for your contribution!

I'm reviewing this and will clean it up as needed.

**Comment by ksatirli** [comment]
Hey @dpowley,

Thanks again for this - I've cleaned this up a little and made sure we have examples for both Audit Log config _and_ Metrics config (and the correct code to execute both of them).

I ran a quick test, but would love it if you could run both examples and report back.

**Comment by ksatirli** [comment]
Once tested and confirmed as working, this will be released as `1.4.0`

**Comment by ksatirli** [comment]
@lucymhdavies any chance you could help in testing this?

Want to make sure this makes sense.

**Comment by lucymhdavies** [comment]
Unrelated to this change:
https://github.com/ksatirli/terraform-hcp-vault-cluster/blob/main/variables.tf#L135-L143

This module only accepts lowercase tier names. The provider actually accepts the uppercase version too, so worth putting a `lower()` around the `var.tier` on line 140 there.

**Comment by lucymhdavies** [comment]
But yeah... from my testing... this works pretty well as a slot-in replacement for defining the `hcp_vault_cluster` resource directly. In my case:


```
/*
resource "hcp_vault_cluster" "this" {
  cluster_id      = "vault-${var.name}"
  hvn_id          = hcp_hvn.vault.hvn_id
  tier            = var.tier
  public_endpoint = var.public_endpoint

  audit_log_config {
    cloudwatch_access_key_id     = var.cloudwatch_creds.key
    cloudwatch_secret_access_key = var.cloudwatch_creds.secret
    cloudwatch_region            = var.cloudwatch_creds.region
  }
}
*/


moved {
  from = hcp_vault_cluster.this
  to   = module.hcp-vault-kerim.hcp_vault_cluster.main
}

module "hcp-vault-kerim" {
  source = "github.com/ksatirli/terraform-hcp-vault-cluster?ref=748e818740bed8a2e498553145a901140f23e0a2"

  cluster_id      = "vault-${var.name}"
  hvn_id          = hcp_hvn.vault.hvn_id
  tier            = lower(var.tier)
  public_endpoint = var.public_endpoint

  audit_log_config = {
    enabled                      = true
    cloudwatch_access_key_id     = var.cloudwatch_creds.key
    cloudwatch_secret_access_key = var.cloudwatch_creds.secret
    cloudwatch_region            = var.cloudwatch_creds.region
  }
}
```


so happy with this as is.

**Comment by ksatirli** [comment]
> Unrelated to this change: https://github.com/ksatirli/terraform-hcp-vault-cluster/blob/main/variables.tf#L135-L143
> 
> This module only accepts lowercase tier names. The provider actually accepts the uppercase version too, so worth putting a `lower()` around the `var.tier` on line 140 there.

Great call out! Added

**Comment by ksatirli** [comment]
Hey @lucymhdavies and @dpowley, thank you both for your inputs!

I've gone through the module and verified everything. 

In the process, I've also updated the HCP provider to `0.78.0` (from `0.76.0`) and bumped the GitHub Actions versions.

@lucymhdavies thanks for the call out on `lower` for `var.tier` - great addition!

**Comment by ksatirli** [comment]
If there are no objections, I'll go ahead and merge this as `1.4.0`.

**Pull request merged**
